spec/features/local_login_spec.rb, spec/support/capybara.rb
This verifies that the active tab on the page after a user types in a bad username and password is still the local login tab.
Add ENV to switch between selenium_chrome and selenium_chrome_headless.
=> Add check to make sure active tab is maintained even after failed login

app/controllers/application_controller.rb, app/helpers/sessions_helper.rb, app/views/devise/sessions/new.html.haml
Also remove unused code in application_controller
Move all the logic used in the session view out into the sessions helper.
Only Github Auth enabled:
All Auth enabled:
=> Cleanup display on login page when only Oauth

spec/simplecov_env.rb
Once #101 and #104 are merged we will have 100% test coverage for the application. We should lock this as the minimum so that we do not drop below this again.
=> Lock minimum app coverage to 100% for PRs

app/errors/rule_revert_error.rb, app/models/rule.rb, config/application.rb, db/migrate/20210810183322_add_description_to_rules.rb, db/schema.rb
https://github.com/mitre/vulcan/issues/128
Notable changes
- implement reverting functionality for controls
- adds a `history` instance method to controls that provides a minimal set of data for describing control history on the frontend
- `project_id` is no longer an audited field
- add `description` attribute to `Rule` model
Users allowed to edit a control also have the ability to revert.
I now notice that there is not a `test/` folder in the project. The below is a short test script (ensure that you have an admin in your DB). 
```ruby
rule1 = Rule.first || Rule.create(project: Project.create(name: "Test Project"))
puts rule1.description
rule1.update(description: "new desc 1")
rule1.update(description: "new desc 2")
puts rule1.history
Rule.revert(User.where(admin: true).first, …
```
=> 128 - implement reverting audited attribute changes on Rules

app/views/projects/index.html.haml, app/views/users/index.html.haml, config/webpacker.yml
Webpacker has a nasty habit of not compiling css files for components and then causing an error in production when they are missing.
https://github.com/rails/webpacker/issues/2342
https://github.com/rails/webpacker/issues/2059#issuecomment-486577228
This adds an override which causes no errors in production but still allows us to leave the stylesheet_pack_tag for when it is needed.
=> Disable webpacker stylesheet errors in production

app/javascript/application.scss, app/javascript/mixins/AlertMixin.vue, app/javascript/packs/application.js, app/views/layouts/application.html.haml
Alerts are now sticky and more visible when performing async actions that generate them. This is particularly helpful on the control editor page where before when an alert was generated it would only ever be seen if the user scrolled to the top of the window - possibly causing confusion on if an action succeeded or not. This has now been changed to make alerts stick to the top of the window.
=> Sticky alerts

app/javascript/components/rules/RuleEditor.vue, app/javascript/components/rules/RuleNavigator.vue, app/javascript/components/rules/RulesCodeEditorView.vue
- Persist advanced editor setting, open controls, and currently selected control across page loads
=> Control editor persistent settings

app/controllers/application_controller.rb, app/controllers/comments_controller.rb, app/controllers/projects_controller.rb, app/controllers/rules_controller.rb, app/javascript/components/rules/RuleEditorHeader.vue, app/javascript/components/rules/RuleNavigator.vue, app/javascript/components/rules/RuleRevertModal.vue, app/javascript/components/rules/Rules.vue, app/javascript/components/rules/RulesCodeEditorView.vue, app/javascript/components/toaster/Toaster.vue, app/javascript/mixins/AlertMixin.vue, app/models/rule.rb, db/migrate/20210910000716_add_unique_index_for_rule_id_and_project_id.rb, db/schema.rb
Notable changes
- Can now add new rules from the control edit page
- Can now delete rules from the control edit page
- JSON error responses from controllers now also respond with a non-200 status
- `alertOrNotifyResponse` mixin is a little more generalized to handle various responses
- fixed a bug related to persisting `openRuleId` across page loads
- `rule.rule_id` now must be unique (relative to project) and non-blank
- added DB index to support this uniqueness constraint
- added `before_create` callback on `Rule` to ensure one check exists (just like disa description)
Open issues/questions:
- What role does a user need to have to create and delete a control?
- ANSWER - only admin for both
=> Create and delete rules

app/controllers/security_requirements_guides_controller.rb, app/models/security_requirements_guide.rb
- change `SecurityRequirementsGuide.from_mapping` to rescue from parsing errors so that user gets usable feedback in the UI
- JSON failure response in `SecurityRequirementsGuidesController#create` can just return `srg.errors.full_messages` and let the `AlertMixIn` handle formatting on the front end.
=> SRG import nicer error feedback

app/constants/rule_constants.rb, app/javascript/components/rules/forms/AdvancedRuleForm.vue, app/javascript/components/rules/forms/BasicRuleForm.vue, app/javascript/components/rules/forms/RuleForm.vue, app/models/rule.rb, db/migrate/20210930182147_add_default_to_rule_status.rb, db/schema.rb
- When status is `Applicable - Does Not Meet`, then users need to be able to configure `mitigation` for the rule. This has been added.
- Added a new status `Not Yet Determined` to rules and set it as the default status
=> Rule form tweaks

app/controllers/rules_controller.rb, app/controllers/users_controller.rb, app/javascript/components/rules/RuleEditorHeader.vue, app/javascript/components/shared/History.vue, app/javascript/components/users/Users.vue, app/lib/vulcan_audit.rb, app/models/application_record.rb, app/models/project_member.rb, app/models/rule.rb, app/models/user.rb, app/views/rules/index.html.haml, app/views/users/index.html.haml, db/migrate/20210930162822_add_audited_user_and_username_to_audits.rb, db/schema.rb
This adds additional logging for user modification events at a global level as well as on a per project level. 
Closes #210
On the project show page:
On the global user management page:
=> Add auditing for global user modifications and project members

app/controllers/components_controller.rb, app/controllers/rules_controller.rb, app/javascript/components/components/AddQuestionsModal.vue, app/javascript/components/components/ProjectComponent.vue, app/javascript/components/rules/RuleEditor.vue, app/javascript/components/rules/RuleHistories.vue, app/javascript/components/rules/RuleRevertModal.vue, app/javascript/components/rules/RulesCodeEditorView.vue, app/javascript/components/rules/RulesReadOnlyView.vue, app/javascript/components/rules/forms/AdditionalAnswerForm.vue, app/javascript/components/rules/forms/AdditionalQuestions.vue, app/javascript/components/rules/forms/AdvancedRuleForm.vue, app/javascript/components/rules/forms/BasicRuleForm.vue, app/javascript/components/rules/forms/CheckForm.vue, app/javascript/components/rules/forms/RuleForm.vue, app/javascript/components/shared/History.vue, app/javascript/mixins/HumanizedTypesMixIn.vue, app/lib/vulcan_audit.rb, app/models/additional_answer.rb, app/models/additional_question.rb, app/models/component.rb, app/models/rule.rb, db/migrate/20211108210022_create_additional_questions.rb, db/migrate/20211109212911_create_additional_answers.rb, db/schema.rb
This adds the ability for users to add arbitrary fields on the component which are then available to be filled out on the individual rules. As of right now they are not available in any export however they do properly revert.
=> Add support for arbitrary fields on Rules from Components

app/constants/import_constants.rb, app/controllers/application_controller.rb, app/models/base_rule.rb, app/models/component.rb, app/models/rule.rb, app/models/security_requirements_guide.rb
Provide better defaults for severity and weight
Undo save if the rules associated with a security requirements guide fail to import. This protects from bad SRGs saving to the database.
Allow components to be destroyed even if they have locked rules in them.
Include mitigations and handle blank severity mappings more gracefully
Show better errors to administrators on 500 errors across the application
=> Better error handling and fixes for import

app/controllers/components_controller.rb, app/javascript/components/components/AddComponentModal.vue, app/javascript/components/components/ComponentCard.vue, app/javascript/components/project/Project.vue, app/models/component.rb, app/models/rule.rb, db/migrate/20211007162847_make_components_child_to_single_project.rb, spec/models/rules_spec.rb
Contains the following changes:
- released component info such as control status, check/fix text, status justifications, etc. are now copied over
- overlaid components should now show up under overlaid components instead of with the non-overlaid ones
- changed all instances of "overlayed" to "overlaid"
Reviews and histories are not copied over because they are stored in the db quite differently than the rest of the data. This might be doable, but would require more intricate work and if it's not necessary for now, we can maybe come back to it after we prioritize other important issues
Closes: https://github.com/mitre/vulcan/issues/361
=> VULCAN 361: Fix overlaid components

app/controllers/rules_controller.rb
Closes: https://github.com/mitre/vulcan/issues/444
=> fix add new control

app/javascript/components/project/DiffViewer.vue
[Issue 410](https://github.com/mitre/vulcan/issues/410): swap diff view comparison
=> VULCAN-410: Swap diff view comparison

app/javascript/components/components/ProjectComponent.vue, app/javascript/components/rules/RuleEditorHeader.vue, app/javascript/components/rules/RuleHistories.vue, app/javascript/components/rules/RuleReviews.vue, app/javascript/components/rules/RuleSatisfactions.vue
https://github.com/mitre/vulcan/issues/452
We'd like to update the workflow for using the Request Review feature to make it more intuitive to the user.
We would like it so that when the authors complete writing a control, they immediately set the control to "Review Requested" from a reviewer. The reviewer can immediately accept a control as complete, which locks it from further editing, or they can ask for more changes. A reviewer can also look at a control and immediately approve it without review if they like.
Management (i.e. reviewers) should be able to tell quickly how much of a STIG is "done" by looking at the count of controls that have been flagged as "Review Requested."
Right now we can take all of these actions but the button that controls reviews is hidden in a collapsed pane …
=> VULCAN-452: Review workflow improvements

app/models/component.rb
Fixed bug #501
Refactored the logic of `Component#duplicate` and `Component#from_mapping` to correctly copy a component and update the rules based a given new srg:
* Fixed the incorrect use of ActiveRecord methods `where` & `pluck`:
* `where` & `pluck` applies on the database level. So if the model instance the      method is being called on is not persisted, the return value is an empty list. Switched to use enumerator methods `select` and `map` instead to get the expected behavior.
* Updated the based_on attribute of the new (copied) component to be the new given srg
* Fixed `#from_mapping` method to correctly check if a new list of rule versions was provided for import or if a null value was given
* Fixed how new `Rule#rule_id` are generated when importing new rules to always generate …
=> 501 copy component fails when selecting a newer srg version and a control has been previously deleted in the source component

Gemfile, Gemfile.lock, app/helpers/export_helper.rb, app/models/rule.rb, spec/factories/components.rb, spec/factories/projects.rb, spec/factories/security_requirements_guides.rb, spec/factories/sequences.rb, spec/helpers/export_helper_spec.rb, spec/rails_helper.rb
=> 495 export to excel does not work if components have the same name

app/helpers/export_helper.rb, app/models/rule.rb
Also updated xccdf export to set the Vul ID value to start with a V- to match InSpec and official Vul ID syntax.
Rule ID and Vul ID should match between InSpec and XCCDF exports so STIG viewer checklist functionality works.
=> 530 populate gid and rid in inspec body data

app/helpers/sessions_helper.rb, app/views/devise/sessions/new.html.haml, config/initializers/0_settings.rb, config/vulcan.default.yml, docs/config.md
- Created an ENV variable (VULCAN_ENABLE_USER_REGISTRATION) in `vulcan.default.yml` file
- Updated the config/initializers accordingly
- Created a Boolean helper function
- Updated the view to display User "Register" form based on the outcome of the Boolean helper function
=> Created an ENV variable for controlling USER registrations on Vulcan app (Enabled by Default)

app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/helpers/application_helper.rb, config/initializers/0_settings.rb, config/vulcan.default.yml, docs/config.md
- Updated `before_action` on the project controllers to disallow non-admin users to create new projects
- Created a function in the application controller
- Added config & introduced an environment variable if some type of deployments want to have users (non-admins) create new projects
- Docs updated
=> Disallow new project creation if not admin by default

Gemfile, Gemfile.lock
Updated the Gemfile by bumpting the csrf gem as per the dependencies listed in here.
https://rubygems.org/gems/omniauth-rails_csrf_protection/versions/1.0.1
=> Bump omniauth-rails_csrf_protection Gem

app/controllers/components_controller.rb, app/javascript/components/components/ProjectComponent.vue, app/javascript/components/project/DiffViewer.vue, app/javascript/components/rules/RuleEditorHeader.vue, app/models/disa_rule_description.rb, app/views/components/show.html.haml, config/routes.rb
This is the backup brach, since the master was rolled back to before the deep linking pr
=> Up to deep linking

app/javascript/components/rules/RuleHistories.vue, app/javascript/components/rules/forms/RuleForm.vue, app/javascript/components/shared/History.vue, app/javascript/mixins/HistoryGroupingMixin.vue
This PR addresses the need to group histories with the same name, created_at, and comment, and adds a tooltip explaining the options for rule status. The changes introduced in this PR include:
1. Extract the common history grouping functionality into a separate mixin named `HistoryGroupingMixin.vue`.
2. Import the `HistoryGroupingMixin.vue` mixin in both the parent (`RuleHistories.vue`) and child (`History.vue`) components.
3. Use the shared mixin's methods in both components to avoid repeating code.
4. Implement a tooltip to display the rule status options and their descriptions.
With these changes, histories with the same name, created_at, and comment are now grouped together, and the history count badge in the parent component displays the correct grouped count. Additionally, users can …
=> Group histories with the same name, created_at, and comment; add tooltip for rule status

app/javascript/components/navbar/App.vue, package.json
This pull request adds the latest release version tag to the Navbar component. The tag is fetched from the GitHub API and displayed next to the "VULCAN" text. It improves the user experience by showing the current release version prominently.
Changes Made:
- Updated the template to include the latest release tag
- Added  a method & mounted property to handle asynchronous API call
- Applied CSS styling to the latest release value for a smaller font size
Fixes #565
=> VULCAN- 565: Add latest release version tag to Navbar component

app/constants/import_constants.rb, app/models/base_rule.rb, app/models/component.rb, app/models/rule.rb, spec/models/rules_spec.rb
- Reading ccis from the imported spreadsheet
- Refactored getting nist_control_family to accomodate for instances of multi ccis
- Refactored inspec code to accomodate for instances of multi ccis
Am I missing a workflow that uses `rule.ident`?
Fix #559
=> VULCAN-559: Support for Multiple CCIs

app/controllers/projects_controller.rb
As highlighted in the below screenshot, when project metadata is updated it is triggering a `rename_project` slack notification.
**Project Metadata Update:**
**Slack Notification Triggered:**
Fix -
- Simplified the project update logic in the update action.
- Introduced the `project_name_changed?` method to check if the project name has changed.
After this `project_rename` slack notification is not triggered if metadata is updated. And the flash messages are also updated accordingly.
=> fix project update logic for detecting name changes correctly

app/models/component.rb, spec/models/components_spec.rb
Fix the import from spreadsheet workflow to properly create rule satisfaction when file contains rules satisfied by many others
Fix #581
=> VULCAN-581: Enhance Import from Spreadsheet workflow 

app/controllers/application_controller.rb, app/controllers/memberships_controller.rb, app/controllers/reviews_controller.rb, app/javascript/components/rules/RuleEditorHeader.vue, app/mailers/user_mailer.rb, app/views/user_mailer/_shared_styles.html.erb, app/views/user_mailer/approve_review.html.erb, app/views/user_mailer/request_review.html.erb, app/views/user_mailer/request_review_changes.html.erb, app/views/user_mailer/revoke_review.html.erb, app/views/user_mailer/welcome_component_member.html.erb, app/views/user_mailer/welcome_project_member.html.erb, config/initializers/smtp_settings.rb
- Invoking the `UserMailer` mailer via the Application Controller
- So, far the SMTP email templates have been added around reviews
- SMTP notifications will be triggered to the `project_admins` CCing the `user` requesting a review.
- `user` will be notified if the review request is `approved` or `revoked`
- If the Admins request for more changes, the `user` will also be notified of the same.
Attaching the sample screenshots
**Welcome Email**
**Request Review**
**Request Additional Changes**
**Approve Request**
**Revoke Request**
=> Enabling SMTP feature to send emails via ActionMailer

app/controllers/reviews_controller.rb, app/javascript/components/rules/RuleEditorHeader.vue
- Prevent locking Applicable - Does Not Meet controls with no mitigations
- Prevent locking Applicable - Inherently Meets Controls with no artifact description
Fix #577 
Fix #578
=> Constrain requirement for locking Applicable -Does Not Meet and Applicable - Inherently Meets controls

app/models/security_requirements_guide.rb, app/models/stig.rb, db/migrate/20230824150144_make_name_not_null_in_stigs.rb, db/schema.rb, lib/tasks/stig_and_srg_puller.rake, spec/controllers/stigs_controller_spec.rb, spec/factories/stigs.rb, spec/models/stig_spec.rb
- Enforced not null constraint on the `name` column of the `stigs` table.
- Updated Stig model to validate the presence of the `name` field.
- Updated `.from_mapping` method of Stig and SecurityRequirementsGuide model to capture the name when initializing the instance
- Updated Stig specs
This will ensure that every STIG has an associated name when created, and prevent display null data on the UI.
=> Fix: Capture STIG Name on Upload

app/controllers/rules_controller.rb, app/javascript/components/rules/RelatedRulesModal.vue
Some Vulcan components are added to multiple projects as overlaid  causing some related rules results to appear as duplicate when grouping by rules by component name only.
- Made the Project info available on the RelatedRulesComponent
- Combined Component's name and project name to fix related rules grouping
=> Fix Related Rules Grouping

app/helpers/export_helper.rb
Added the XML Attribute and tested the Vulcan XCCDF XML Export with the latest STIG Viewer 3.x.
Attached Screenshots below - 
**Vulcan XCCDF Export generating fixref attribute tags for every rule**
**STIG Viewer 3.x Displaying the FixText Successfully Without any Issues**
=> Added fixref attribute to fixtext XML tag for compatibility with stig-viewer-3x

app/controllers/projects_controller.rb, app/helpers/export_helper.rb, app/javascript/components/project/Project.vue, spec/helpers/export_helper_spec.rb
Vulcan is facing memory issues when attempting to excel export large projects. 
The implemented solution break data export into smaller batches to reduce memory consumption. This is done by allowing users to select which components they would like to export.
Fix #600
=> Enable user to select which component to excel export

app/controllers/rule_satisfactions_controller.rb, app/controllers/rules_controller.rb, app/models/component.rb, app/models/rule.rb, db/seeds.rb
=> Ensure a rule's inspec code is updated after establishing rule satisfaction or reverting change on a rule

app.json
As announced on May 1, 2024, Heroku Postgres mini and basic plans will reach end-of-life (EOL) on May 22, 2024.
Heimdall was using heroku-postgresql:mini.
Make the necessary changes in the app.json, update to the new Essential plan to:
heroku-postgresql:mini → heroku-postgresql:essential-0
=> Upgrade to New Heroku Plan
