mitre/vulcan

app/models/user.rb

Fixed duplicate errors displaying on registration

Duplicate error

---

app/mailers/application_mailer.rb
app/models/user.rb
config/initializers/0_settings.rb
config/initializers/devise.rb
config/vulcan.default.yml
spec/controllers/registrations_controller_spec.rb
spec/support/login_helpers.rb

Email is now configurable through and ENV
closes #91

Email config

---

.github/workflows/run-tests.yml
config/vulcan.default.yml
spec/controllers/registrations_controller_spec.rb

Prefix all ENVs with VULCAN_ to ensure uniqueness

---

app/controllers/rules_controller.rb
app/errors/rule_locked_error.rb
app/models/rule.rb
app/models/user.rb
db/migrate/20210805212212_create_rules.rb
db/migrate/20210806201256_add_admin_to_users.rb
db/schema.rb

* Create Rules table with lock column
* Add an admin column to User to facilitate basic unlocking
* Add callback to Rule to prevent further editing if lock is set
* Add Rule#unlock to allow unlocking Rules when permissions are correct
* Add User#can_unlock to manage permissions around unlocking Rules

Add support for locking and unlocking Rules

---

Gemfile.lock
app/controllers/application_controller.rb
app/controllers/rules_controller.rb
app/javascript/components/rules/RuleComments.vue
app/javascript/components/rules/RuleEditorHeader.vue
app/javascript/components/rules/RuleHistories.vue
app/javascript/components/rules/RuleNavigator.vue
app/javascript/components/rules/Rules.vue
app/javascript/components/rules/RulesCodeEditorView.vue
app/javascript/packs/application.js
app/javascript/packs/rules.js
app/models/rule.rb
config/routes.rb

Notable changes:
- allows locking/unlocking controls from the edit page
- removed unused revert code
- axios default `axios.defaults.headers.common['Accept'] = 'application/json'` on each request we currently make

Lockable controls

---

babel.config.js
package.json
yarn.lock

Silence errors coming from babel

Update all yarn dependencies to latest versions

---

Gemfile

This fixes an issue where Heroku couldn't seed data

Add FFaker to production dependencies

---

app/javascript/components/project_members/NewProjectMember.vue

Notable Changes
- The role descriptions in the new member modal are now in the correct order
- The email input field now takes up the available horizontal space in the new member modal

Visual bug fixes on the project member page

---

app/controllers/rules_controller.rb
app/javascript/components/rules/Rules.vue
app/models/user.rb
app/views/rules/index.html.haml

- Pass the current user's effective project permissions to the Rules Vue component

Pass permission level to Rules.vue

---

app/javascript/components/rules/RuleEditor.vue
app/javascript/components/rules/forms/AdvancedRuleForm.vue
app/javascript/components/rules/forms/BasicRuleForm.vue
app/javascript/components/rules/forms/CheckForm.vue
app/javascript/components/rules/forms/DisaRuleDescriptionForm.vue
app/javascript/components/rules/forms/RuleDescriptionForm.vue
app/javascript/components/rules/forms/RuleForm.vue

- user can now toggle between a basic rule form and advanced rule form
- components have been broken up to support this without duplicating form code

Break rule form into a toggle between basic and advanced rule editing

---

.github/workflows/push-to-docker.yml

Fixes disabled auto-builds for docker.

Push to Dockerhub on every merge to master

---

Gemfile
Gemfile.lock
lib/tasks/create_admin.rake

Add task for creating administrators from command line

---

app/controllers/components_controller.rb
app/javascript/components/components/ProjectComponent.vue
app/javascript/components/components/UpdateMetadataModal.vue
app/models/component.rb
app/models/component_metadata.rb
db/migrate/20211101152514_create_component_metadata_table.rb
db/schema.rb

Closes https://github.com/mitre/vulcan/issues/283

Add metadata to components

---

app/javascript/components/rules/forms/BasicRuleForm.vue
app/javascript/components/rules/forms/RuleForm.vue

Update fields displayed on 'Applicable - Configurable' display

---

app/constants/rule_constants.rb
app/javascript/components/components/ProjectComponent.vue
app/javascript/components/rules/RuleEditor.vue
app/javascript/components/rules/Rules.vue
app/javascript/components/rules/RulesCodeEditorView.vue
app/javascript/components/rules/RulesReadOnlyView.vue
app/javascript/components/rules/forms/BasicRuleForm.vue
app/javascript/components/rules/forms/RuleForm.vue
app/models/rule.rb
app/views/components/show.html.haml
app/views/rules/index.html.haml

Map Low/Medium/High to CAT I, CAT II, CAT III

---

.rubocop.yml
app/controllers/components_controller.rb
app/controllers/rule_satisfactions_controller.rb
app/controllers/rules_controller.rb
app/javascript/components/components/ProjectComponent.vue
app/javascript/components/rules/RuleEditor.vue
app/javascript/components/rules/RuleEditorHeader.vue
app/javascript/components/rules/RuleHistories.vue
app/javascript/components/rules/RuleNavigator.vue
app/javascript/components/rules/RuleReviews.vue
app/javascript/components/rules/RuleSatisfactions.vue
app/javascript/components/rules/Rules.vue
app/javascript/components/rules/RulesCodeEditorView.vue
app/javascript/components/rules/RulesReadOnlyView.vue
app/javascript/components/rules/forms/AdvancedRuleForm.vue
app/javascript/components/rules/forms/BasicRuleForm.vue
app/javascript/components/rules/forms/RuleForm.vue
app/javascript/mixins/SortRulesMixin.vue
app/models/base_rule.rb
app/models/component.rb
app/models/concerns/rule_satisfaction_validator.rb
app/models/rule.rb
app/models/rule_satisfaction.rb
app/views/layouts/application.html.haml
config/routes.rb
db/migrate/20211103190520_create_rule_satisfactions.rb
db/schema.rb

Closes: https://github.com/mitre/vulcan/issues/285

Setup 'Application - Configurable Duplicate' controls within an SRG

---

app/models/concerns/prefix_validator.rb
spec/models/components_spec.rb

Allow alphas in second section of prefix

---

app/javascript/components/shared/CommentModal.vue

Closes: https://github.com/mitre/vulcan/issues/320

VULCAN-320: Make comment field optional

---

app/javascript/components/rules/RuleHistories.vue

Closes: https://github.com/mitre/vulcan/issues/318

VULCAN-318: Rename histories

---

app/controllers/components_controller.rb
app/javascript/components/components/ComponentCard.vue

Closes: https://github.com/mitre/vulcan/issues/319

VULCAN-319: Allow ability to export before a component is released

---

app/javascript/components/rules/RuleNavigator.vue

Closes: https://github.com/mitre/vulcan/issues/308

VULCAN-308: Bulk close controls

---

app/models/component.rb

Closes: https://github.com/mitre/vulcan/issues/326

VULCAN-326: Order csv export

---

app/javascript/components/components/ProjectComponent.vue
app/javascript/components/rules/RuleReviews.vue
app/javascript/components/rules/RuleSatisfactions.vue
app/javascript/components/rules/RulesReadOnlyView.vue

Closes: https://github.com/mitre/vulcan/issues/317

VULCAN-317: Add rule history to read only view

---

app/javascript/application.scss
app/javascript/components/rules/RuleNavigator.vue
app/javascript/components/rules/RuleReviews.vue
app/javascript/components/rules/Rules.vue
app/javascript/components/rules/RulesCodeEditorView.vue
app/javascript/components/rules/RulesReadOnlyView.vue

This makes it easier to open additional controls without requiring the user to scroll up and down the page.

Isolate sidebar scrolling from rest of page

---

app/javascript/components/rules/RuleSatisfactions.vue
app/models/base_rule.rb

Closes: https://github.com/mitre/vulcan/issues/316

VULCAN-316: Also Satisfies should be the SRG ID or the SRG + STIG ID, not only the STIG ID

---

app/javascript/application.scss
app/javascript/components/rules/RuleReviews.vue
app/javascript/components/shared/History.vue

Closes: https://github.com/mitre/vulcan/issues/339

VULCAN-339: Display line breaks in comments

---

app/javascript/components/navbar/App.vue
config/locales/devise.en.yml

Closes: https://github.com/mitre/vulcan/issues/337

VULCAN-337: Error message when logging out

---

app/models/user.rb
config/initializers/devise.rb
config/vulcan.default.yml
docs/config.md

Closes: https://github.com/mitre/vulcan/issues/328#issuecomment-1005220992

VULCAN-328: Add session timeout

---

app/javascript/components/components/NewComponentModal.vue

Closes: https://github.com/mitre/vulcan/issues/346

VULCAN-346: Remove SRG suggestions limit

---

Gemfile
Gemfile.lock
app/constants/import_constants.rb
app/controllers/components_controller.rb
app/javascript/components/components/NewComponentModal.vue
app/javascript/components/project/Project.vue
app/javascript/mixins/AlertMixin.vue
app/models/base_rule.rb
app/models/component.rb
app/models/rule.rb
app/models/srg_rule.rb

This adds a new button to the application which allows users to upload existing filled out spreadsheets. Closes #124

Add support for importing existing Excel spreadsheet

---

app/models/component.rb

This fixes an issue where during import any rules not listed will not be included when editing in the browser.

Include missing Rules in import from spreadsheet

---

app/controllers/reviews_controller.rb
app/controllers/rules_controller.rb

Closes: https://github.com/mitre/vulcan/issues/364

VULCAN-364: Fix rule viewing permissions

---

app/controllers/reviews_controller.rb
app/javascript/components/components/ComponentCard.vue
app/javascript/components/components/LockControlsModal.vue
app/models/rule.rb
config/routes.rb

Closes: https://github.com/mitre/vulcan/issues/360

VULCAN-360: Bulk lock rules

---

app/controllers/projects_controller.rb
app/javascript/components/project/Project.vue
app/models/project.rb

Closes: https://github.com/mitre/vulcan/issues/334

VULCAN-334: Improve visibility from project dashboard

---

app/models/component.rb
app/models/security_requirements_guide.rb

Closes: https://github.com/mitre/vulcan/issues/301

VULCAN-301: STIG ID assignment should be ordered by SRG ID

---

app/javascript/components/rules/RuleEditorHeader.vue
app/javascript/components/rules/forms/NewRuleModalForm.vue

Closes: https://github.com/mitre/vulcan/issues/381

VULCAN-381: Update Duplicate Control button to Clone Control

---

app/controllers/components_controller.rb
app/javascript/components/project/DiffViewer.vue
config/routes.rb

Closes: https://github.com/mitre/vulcan/issues/400

VULCAN-400: Diff viewer allow comparison with like released components

---

app/controllers/application_controller.rb
app/controllers/security_requirements_guides_controller.rb
app/helpers/application_helper.rb
app/javascript/components/security_requirements_guides/SecurityRequirementsGuides.vue
app/javascript/components/security_requirements_guides/SecurityRequirementsGuidesTable.vue
app/views/security_requirements_guides/index.html.haml

Closes: https://github.com/mitre/vulcan/issues/369

VULCAN-369: Fix view SRG permissions

---

app/controllers/reviews_controller.rb

Closes: https://github.com/mitre/vulcan/issues/373

VULCAN-373: Fix all lock feature for duplicate controls

---

app/controllers/components_controller.rb
app/javascript/components/project/Project.vue
app/javascript/components/project/RevisionHistory.vue
app/models/rule.rb
config/routes.rb

Closes: https://github.com/mitre/vulcan/issues/143

VULCAN-143: Ability to create a high-level version/release history document for a component/project

---

app/controllers/components_controller.rb
app/controllers/projects_controller.rb
app/controllers/security_requirements_guides_controller.rb
app/javascript/components/components/NewComponentModal.vue
app/javascript/components/project/Project.vue
app/javascript/components/projects/Projects.vue
app/models/component.rb

Closes: https://github.com/mitre/vulcan/issues/138

VULCAN-138: Ability to start new revision of STIG

---

app/controllers/components_controller.rb
app/controllers/rules_controller.rb
app/javascript/components/components/ProjectComponent.vue
app/javascript/components/rules/RuleSatisfactions.vue
app/javascript/components/rules/RulesCodeEditorView.vue
app/javascript/components/shared/History.vue
app/lib/vulcan_audit.rb
app/models/component.rb
app/models/rule.rb
db/migrate/20220420164249_add_deleted_at_to_base_rules.rb
db/schema.rb

Closes: https://github.com/mitre/vulcan/issues/371

VULCAN-371: Add revision history at a component level

---

app/javascript/mixins/HumanizedTypesMixIn.vue

Closes: https://github.com/mitre/vulcan/issues/312

content field should be called check

---

app/constants/rule_constants.rb
app/javascript/components/rules/forms/RuleForm.vue

low was incorrect mapped to CAT I and high to CAT III

Fix severity mapping

---

app/controllers/components_controller.rb
app/lib/vulcan_audit.rb

Closes: https://github.com/mitre/vulcan/issues/429

VULCAN-429: Fix deleting a control prevents the deleting of the component

---

app/controllers/components_controller.rb
app/models/component.rb
app/models/rule.rb

Closes: https://github.com/mitre/vulcan/issues/433

VULCAN-433: Modify rules_count to exclude deleted rules

---

app/models/rule.rb
db/migrate/20220204072642_add_inspec_code_to_rules.rb

Closes: https://github.com/mitre/vulcan/issues/419

VULCAN-419: Sort Inspec tags

---

app/controllers/components_controller.rb
app/javascript/components/rules/FindAndReplace.vue
app/javascript/components/rules/FindAndReplaceResult.vue
app/javascript/components/rules/RuleNavigator.vue
app/javascript/components/shared/CommentModal.vue
app/javascript/mixins/FindAndReplaceMixin.vue
config/routes.rb

Closes: https://github.com/mitre/vulcan/issues/454
Currently supports find and replace for the following fields:
- title
- vulnerability discussion
- check
- fixtext
- vendor comments

VULCAN-454: Implement find and replace

---

app/javascript/components/components/AddComponentModal.vue
app/javascript/components/components/NewComponentModal.vue
app/javascript/mixins/DisplayedComponentMixin.vue

Closes: https://github.com/mitre/vulcan/issues/415

VULCAN-415: Show version and release for overlaid components suggestions

---

app/javascript/components/rules/forms/RuleForm.vue

Closes: https://github.com/mitre/vulcan/issues/445

VULCAN-445: Title box visibility

---

app/controllers/rule_satisfactions_controller.rb

Closes: https://github.com/mitre/vulcan/issues/449

VULCAN-449: Fix mark as duplicate for proj/comp admin/authors

---

app/javascript/components/rules/RuleEditorHeader.vue

Closes: https://github.com/mitre/vulcan/issues/457

VULCAN-457: Add tooltip for mark as duplicate

---

app/javascript/components/rules/forms/CheckForm.vue
app/javascript/components/rules/forms/DisaRuleDescriptionForm.vue
app/javascript/components/rules/forms/RuleForm.vue

Closes: https://github.com/mitre/vulcan/issues/447

VULCAN-447: Enable context-aware popover help icons, depending on Status field

---

app/javascript/components/memberships/NewMembership.vue
app/javascript/components/rules/RuleEditor.vue

Quick typo fixes noticed during demos.
Signed-off-by: Will Dower <wdower@mitre.org>

fixes #475

---

README.md

Should resolve #483 
Signed-off-by: Christopher Hinchey <chinchey@mitre.org>

Fix GitHub logo in README

---

app/javascript/application.scss
app/javascript/components/rules/RuleEditorHeader.vue

470 change the color of the mark as duplicate button

---

app/controllers/projects_controller.rb
app/helpers/export_helper.rb
app/javascript/components/project/Project.vue
spec/helpers/export_helper_spec.rb

Signed-off-by: Vanessa Fotso <vfotso@mitre.org>

Completed #496

---

app/constants/export_constants.rb
app/constants/import_constants.rb
app/helpers/export_helper.rb
app/models/component.rb
app/models/rule.rb

- Updated Component/Project spreadsheet export to include `InSpec Control Body`.
- Updated Component import from spreadsheet workflow to parse `InSpec Control Body` if provided.

VULCAN-563: Export/Import inspec control body

---

app/controllers/components_controller.rb
app/javascript/components/components/UpdateComponentDetailsModal.vue

Just in case someone mess up details on component creation or you just want to update the details.

Enabled editing component STIG ID prefix

---

app/javascript/components/rules/RuleNavigator.vue

- Added a toggle to enable users to group & sort controls by SRG ID

Adding the option to group/sort controls by SrG ID

---

app/javascript/components/rules/RelatedRulesModal.vue

Modal form would not load the list if certain data was null, and modal form would not function correctly.

If null data just return for related info

---

app/javascript/packs/project.js
app/javascript/packs/project_component.js
app/javascript/packs/project_components.js
app/javascript/packs/stig.js
package.json
yarn.lock

- Original: 18 vulnerabilities (6 Low | 9 Moderate | 2 High | 1 Critical)  
- Final: 4 vulnerabilities (1 Low | 3 Moderate | 0 High | 0 Critical)
- **78% reduction, eliminated ALL critical and high vulnerabilities**
- axios: 1.11.0 → 1.12.2 (DoS vulnerability)
- bootstrap: ^4.4.1 → 4.6.2 (Final Bootstrap 4, security patches)
- vue-linkify → v-linkify (Secure alternative with XSS prevention)
- Yarn resolutions for nested dependencies:
- loader-utils: >=1.4.1 (CRITICAL prototype pollution) 
- json5: >=1.0.2 (HIGH prototype pollution)
- postcss: >=8.4.31 (MODERATE ReDoS vulnerabilities)
- brace-expansion: >=1.1.12 (LOW ReDoS vulnerabilities)
- ✅ Build verification: All JavaScript assets compile successfully
- ✅ Functionality preserved: Same linkify behavior with better security
- ✅ No …

chore: Comprehensive security updates - eliminate all critical/high vulnerabilities
